eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: api-gateway
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: root
    url: jdbc:h2:~/db/api-gateway;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console
      enabled: true
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 9191

api-gateway:
  ribbon:
    listOfServers: http://localhost:9191
