eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  application:
    name: payment-service
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: user
    url: jdbc:h2:~/db/payment-service;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  h2:
    console:
      settings:
        trace: true
        web-allow-others: false
      path: /h2-console
      enabled: true
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 9091
payment-service:
  ribbon:
    listOfServers: http://localhost:9091